services:
  ai_delver_ai:
    build:
      context: .
    image: ai_delver
    container_name: ai_delver
    working_dir: /app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    user: "${UID}:${GID}"
